#!/bin/bash

echo "Running git pre-commit hook"

./gradlew ktlintCheck
ktlintCheckStatus=$?

./gradlew detekt
detektStatus=$?

# return 1 if any check fails
if [[ $ktlintCheckStatus -ne 0 || $detektStatus -ne 0 ]]; then
    echo "Code style violations or code issues found. Please fix them before committing."
    exit 1
else
    exit 0
fi