openapi: "3.1.0"
info:
  title: "HobbyMatch_Backend API"
  description: "HobbyMatch_Backend API"
  version: "1.0.0"
servers:
  - url: "https://HobbyMatch_Backend"
paths:
  /hello:
    get:
      summary: "GET hello"
      operationId: "hello"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "string"